colorscheme solarized-dark-termcolors
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ column 72 default,black
add-highlighter global/ column 100 black,red+rb
add-highlighter global/ regex \b(TODO|FIXME|NOTE)\b 0:default+rb

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|c|cpp) %{
    lsp-enable-window
}

map global insert <c-o> %{<a-;>o!<esc><backspace>}
map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
map global user n %{i[`<esc>a`]<esc>2<s-h>} -docstring "Create rust doc link"
map global user ` %{i`<esc>a`<esc><s-h>} -docstring "Surround with backticks"
map global user \' %{i'<esc>a'<esc><s-h>} -docstring "Surround with ticks"
map global user \" %{i"<esc>a"<esc><s-h>} -docstring "Surround with quotes"
map global user ( %{i(<esc>a)<esc><s-h>} -docstring "Surround with parens"
map global user { %{i{<esc>a}<esc><s-h>} -docstring "Surround with braces"
map global user [ %{i[<esc>a]<esc><s-h>} -docstring "Surround with brackets"
map global user < %{i<lt><esc>a<gt><esc><s-h>} -docstring "Surround with angle brackets"
